User entitiy
CSC207-2022F-UofT/course-project-recipez pull request #19
Opened 2022-10-31 21:52 UTC by Shaffaan

I have created a basic abstracter class and a user class that extends it. Further created an example of the main class(this needs to be edited later)
 Please review and make sure it is okay and review changes

2022-10-31 21:56 UTC, fishyvishy approved these changes
I've reviewed the changes. Not sure whether abstractUser is necessary, but will keep for now in case we need it.

2022-10-31 22:00 UTC, EricKarpovits requested changes

2022-10-31 22:00 UTC, EricKarpovits commented on src/main/java/entities/abstractUser.java
> +public abstract class abstractUser {
Consider using AbstractUser

2022-10-31 22:03 UTC, EricKarpovits approved these changes

2022-11-04 01:41 UTC, Zhuofan-Y approved these changes
A good start of entities!

2022-11-07 21:40 UTC, merged