Result page
CSC207-2022F-UofT/course-project-recipez pull request #27
Opened 2022-11-19 01:19 UTC by takeachangs

Results page with examples of recipes. When clicked it will open the full recipes on the browser. Will make it into a loop with inputs from recipe builder presenter once it is done.

2022-11-19 02:34 UTC, EricKarpovits requested changes

2022-11-19 02:34 UTC, EricKarpovits commented on src/main/java/presenters/ButtonCreator.java
> +public class ButtonCreator {
Add docstrings for the class and methods please

2022-11-19 02:34 UTC, EricKarpovits commented on src/main/java/presenters/ResultsPageFrame.java
> +public class ResultsPageFrame extends JFrame implements RecipeBuilderPresenter {
Add docstrings for the class and methods please

2022-11-19 02:34 UTC, EricKarpovits commented on src/main/java/presenters/ResultsPageLauncher.java
> +public class ResultsPageLauncher {
Add docstrings for the class and methods please

2022-11-22 00:47 UTC, takeachangs reviewed
Added docstrings

2022-11-22 01:21 UTC, EricKarpovits approved these changes
Great work @takeachangs!

2022-11-22 04:37 UTC, fonuxxine approved these changes
Your docstrings explain nicely different parts of your code.

2022-11-22 04:47 UTC, fishyvishy approved these changes
Well done. Good implementation using MVVM.

2022-11-22 04:47 UTC, fishyvishy commented on src/main/java/UI/resultPage/ResultsPageMain.java
> +/*package presenters;
should probably delete this class altogether.

2022-11-22 04:59 UTC, merged